import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:path/path.dart' as p;

/// End-to-end test: invokes the `print_widget scaffold` command via
/// `Process.run` and asserts the emitted Dart is well-formed.
void main() {
  group('print_widget scaffold — integration', () {
    late Directory tmpDir;
    late String cliPath;
    late String fixturesDir;

    setUpAll(() {
      cliPath = p.absolute(
        p.join(Directory.current.path, 'bin', 'print_widget.dart'),
      );
      fixturesDir = p.absolute(
        p.join(Directory.current.path, 'test', 'codegen', 'fixtures'),
      );
    });

    setUp(() {
      tmpDir = Directory.systemTemp.createTempSync('pw_scaffold_test_');
    });

    tearDown(() {
      if (tmpDir.existsSync()) tmpDir.deleteSync(recursive: true);
    });

    Future<ProcessResult> runScaffold(List<String> args) {
      return Process.run(
        'dart',
        ['run', cliPath, 'scaffold', ...args],
        workingDirectory: tmpDir.path,
      );
    }

    test('icon_badge: emits clean Dart with no TODO markers', () async {
      final spec = p.join(fixturesDir, 'icon_badge.spec.json');
      final r = await runScaffold([
        '--spec=$spec',
        '--class-name=_IconBadgeScaffold',
        '--stdout',
      ]);
      expect(r.exitCode, 0,
          reason: 'stderr: ${r.stderr}\nstdout: ${r.stdout}');
      final source = r.stdout as String;

      // No TODO markers for a canary fixture.
      expect(source, isNot(contains('// TODO:')));

      // Must survive `dart format` (exit cleanly). We don't require
      // idempotence — the emitter makes minor indentation choices that dart
      // format tightens up, which is fine.
      final scratch = File(p.join(tmpDir.path, 'scratch.dart'));
      scratch.writeAsStringSync(source);
      final fmt = await Process.run('dart', ['format', scratch.path]);
      expect(fmt.exitCode, 0, reason: 'dart format failed: ${fmt.stderr}');
      // Formatter must not have injected any TODO markers either.
      expect(scratch.readAsStringSync(), isNot(contains('// TODO:')));
    });

    test('delta_indicator emits no TODO markers', () async {
      final spec = p.join(fixturesDir, 'delta_indicator.spec.json');
      final r = await runScaffold([
        '--spec=$spec',
        '--class-name=_DeltaIndicatorScaffold',
        '--stdout',
      ]);
      expect(r.exitCode, 0);
      expect(r.stdout as String, isNot(contains('// TODO:')));
    });

    test('status_badge emits no TODO markers', () async {
      final spec = p.join(fixturesDir, 'status_badge.spec.json');
      final r = await runScaffold([
        '--spec=$spec',
        '--class-name=_StatusBadgeScaffold',
        '--stdout',
      ]);
      expect(r.exitCode, 0);
      expect(r.stdout as String, isNot(contains('// TODO:')));
    });

    test('--output writes a file and creates parent directories', () async {
      final spec = p.join(fixturesDir, 'icon_badge.spec.json');
      final outPath = p.join(tmpDir.path, 'lib', 'gen', 'icon_badge_scaffold.dart');
      final r = await runScaffold([
        '--spec=$spec',
        '--class-name=_IconBadgeScaffold',
        '--output=$outPath',
      ]);
      expect(r.exitCode, 0, reason: 'stderr: ${r.stderr}');
      final out = File(outPath);
      expect(out.existsSync(), isTrue);
      final content = out.readAsStringSync();
      expect(content, contains('class _IconBadgeScaffold'));
      expect(content, contains('// AUTO-GENERATED by print_widget scaffold'));
    });

    test('refuses to overwrite without --force', () async {
      final spec = p.join(fixturesDir, 'icon_badge.spec.json');
      final outPath = p.join(tmpDir.path, 'existing.dart');
      File(outPath).writeAsStringSync('// pre-existing\n');
      final r = await runScaffold([
        '--spec=$spec',
        '--class-name=_IconBadgeScaffold',
        '--output=$outPath',
      ]);
      expect(r.exitCode, isNot(0));
      expect(
        File(outPath).readAsStringSync(),
        '// pre-existing\n',
        reason: 'should not overwrite without --force',
      );
    });

    test('--force overwrites existing output', () async {
      final spec = p.join(fixturesDir, 'icon_badge.spec.json');
      final outPath = p.join(tmpDir.path, 'existing.dart');
      File(outPath).writeAsStringSync('// pre-existing\n');
      final r = await runScaffold([
        '--spec=$spec',
        '--class-name=_IconBadgeScaffold',
        '--output=$outPath',
        '--force',
      ]);
      expect(r.exitCode, 0);
      expect(
        File(outPath).readAsStringSync(),
        isNot(contains('pre-existing')),
      );
    });

    test('--json emits machine-readable result', () async {
      final spec = p.join(fixturesDir, 'icon_badge.spec.json');
      final outPath = p.join(tmpDir.path, 'out.dart');
      final r = await runScaffold([
        '--spec=$spec',
        '--class-name=_IconBadgeScaffold',
        '--output=$outPath',
        '--json',
      ]);
      expect(r.exitCode, 0);
      final decoded = jsonDecode(r.stdout as String) as Map<String, dynamic>;
      expect(decoded['className'], '_IconBadgeScaffold');
      expect(decoded['hasSvg'], true);
      expect(decoded['todoCount'], 0);
      expect(decoded['output'], outPath);
    });

    test('auto-derives --class-name and --output from spec path', () async {
      final spec = p.join(tmpDir.path, 'hero_banner_spec.json');
      File(spec).writeAsStringSync(jsonEncode({
        'root': {
          'tag': 'span',
          'text': 'hi',
          'typography': {'fontSize': 12, 'fontWeight': 400, 'color': '#000000'},
        },
      }));
      final r = await runScaffold(['--spec=$spec']);
      expect(r.exitCode, 0, reason: 'stderr: ${r.stderr}');
      final expected = File(
        p.join(tmpDir.path, 'lib', 'scaffolds', 'hero_banner_scaffold.dart'),
      );
      expect(expected.existsSync(), isTrue,
          reason: 'expected auto-output at ${expected.path}');
      final content = expected.readAsStringSync();
      expect(content, contains('class _HeroBannerScaffold'));
    });

    test('requires --spec', () async {
      final r = await runScaffold([]);
      expect(r.exitCode, isNot(0));
      expect(r.stderr.toString(), contains('--spec'));
    });

    test('rejects missing spec file', () async {
      final r = await runScaffold(['--spec=/nonexistent/nope_spec.json']);
      expect(r.exitCode, isNot(0));
      expect(r.stderr.toString(), contains('not found'));
    });

    test('rejects malformed JSON spec', () async {
      final bad = File(p.join(tmpDir.path, 'bad.json'));
      bad.writeAsStringSync('{not valid json');
      final r = await runScaffold(['--spec=${bad.path}', '--stdout']);
      expect(r.exitCode, isNot(0));
      expect(r.stderr.toString(), contains('invalid JSON'));
    });
  });
}
