name: print_widget_example
description: Example usage of print_widget package.

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  print_widget_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
