name: print_widget_example
description: Example usage of print_widget package.

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  print_widget_flutter:
    path: ../

flutter:
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont-Regular.ttf
        - asset: assets/fonts/CustomFont-Bold.ttf
          weight: 700

dev_dependencies:
  flutter_test:
    sdk: flutter
