import 'dart:convert';
import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:yaml/yaml.dart';

class GenerateCommand extends Command<void> {
  GenerateCommand() {
    argParser
      ..addOption(
        'name',
        abbr: 'n',
        help: 'Generate a specific widget by name.',
      )
      ..addOption(
        'device',
        abbr: 'd',
        help: 'Override the device frame (e.g. iphone_15_pro, pixel_7).',
      )
      ..addFlag(
        'all-devices',
        help: 'Generate screenshots for all popular devices.',
        negatable: false,
      )
      ..addOption(
        'config',
        abbr: 'c',
        help: 'Path to print_widget.yaml config file.',
        defaultsTo: 'print_widget.yaml',
      );
  }

  @override
  String get name => 'generate';

  @override
  String get description =>
      'Generate widget screenshots by running Flutter golden tests.';

  @override
  Future<void> run() async {
    final configPath = argResults!['config'] as String;
    final filterName = argResults!['name'] as String?;
    final deviceOverride = argResults!['device'] as String?;
    final allDevices = argResults!['all-devices'] as bool;

    // 1. Read print_widget.yaml
    final yamlFile = File(configPath);
    if (!yamlFile.existsSync()) {
      stderr.writeln(
        'Config file not found: $configPath\n'
        'Run "print_widget init" first.',
      );
      exitCode = 1;
      return;
    }

    final yamlContent = loadYaml(yamlFile.readAsStringSync()) as YamlMap;
    final dartConfigFile = yamlContent['config_file'] as String? ??
        'test/prints/print_config.dart';
    final outputDir =
        yamlContent['output_dir'] as String? ?? 'test/prints/output';
    final defaultDevice =
        yamlContent['default_device'] as String? ?? 'iphone_15_pro';
    final manifestEnabled = yamlContent['manifest'] as bool? ?? true;

    // Verify the Dart config file exists
    if (!File(dartConfigFile).existsSync()) {
      stderr.writeln(
        'Dart config file not found: $dartConfigFile\n'
        'Run "print_widget init" to create a template.',
      );
      exitCode = 1;
      return;
    }

    // Ensure output dir exists
    Directory(outputDir).createSync(recursive: true);

    // 2. Generate temporary test file
    final tempDir = Directory('.dart_tool/print_widget');
    tempDir.createSync(recursive: true);

    final tempTestFile = File('${tempDir.path}/print_test.dart');

    final effectiveDevice = deviceOverride ?? defaultDevice;

    tempTestFile.writeAsStringSync(_generateTestContent(
      dartConfigFile: dartConfigFile,
      outputDir: outputDir,
      device: effectiveDevice,
      filterName: filterName,
      allDevices: allDevices,
    ));

    stdout.writeln('print_widget: Generating screenshots...');
    stdout.writeln('  Config: $dartConfigFile');
    stdout.writeln('  Output: $outputDir');
    if (filterName != null) {
      stdout.writeln('  Filter: $filterName');
    }
    if (allDevices) {
      stdout.writeln('  Devices: all popular');
    } else {
      stdout.writeln('  Device: $effectiveDevice');
    }
    stdout.writeln('');

    // 3. Run flutter test --update-goldens
    final result = await Process.run(
      'flutter',
      ['test', '--update-goldens', tempTestFile.path],
      runInShell: true,
    );

    if (result.stdout.toString().isNotEmpty) {
      stdout.write(result.stdout);
    }

    if (result.exitCode != 0) {
      stderr.writeln('Flutter test failed (exit code ${result.exitCode}):');
      if (result.stderr.toString().isNotEmpty) {
        stderr.write(result.stderr);
      }
      exitCode = result.exitCode;
      return;
    }

    // 4. Generate manifest.json if enabled
    if (manifestEnabled) {
      _generateManifest(outputDir);
    }

    // 5. Summary
    stdout.writeln('');
    stdout.writeln('Screenshots generated successfully!');
    stdout.writeln('  Output directory: $outputDir');
    if (manifestEnabled) {
      stdout.writeln('  Manifest: $outputDir/manifest.json');
    }
  }
}

String _generateTestContent({
  required String dartConfigFile,
  required String outputDir,
  required String device,
  String? filterName,
  bool allDevices = false,
}) {
  // Convert relative config path to a package-style import.
  // The config file is relative to the project root, and the test file
  // is at .dart_tool/print_widget/print_test.dart, so we need to go up
  // two directories.
  final configImport = '../../$dartConfigFile';

  return '''
// AUTO-GENERATED by print_widget CLI. Do not edit.
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter/material.dart';
import 'package:print_widget/print_widget.dart';

import '$configImport';

void main() {
  group('print_widget generate', () {
    testWidgets('generate screenshots', (tester) async {
      final session = printSession;
      final entries = printList;

      for (final entry in entries) {
        ${filterName != null ? "if (entry.name != '$filterName') continue;" : ''}

        final devices = entry.devices ??
            ${allDevices ? 'DeviceFrame.popular' : "[_resolveDevice('$device') ?? session.defaultDevice ?? DeviceFrame.iPhone15Pro]"};

        for (final deviceFrame in devices) {
          // Configure surface
          await tester.binding.setSurfaceSize(deviceFrame.size);
          tester.view.physicalSize = deviceFrame.size * deviceFrame.pixelRatio;
          tester.view.devicePixelRatio = deviceFrame.pixelRatio;

          // Wrap with app wrapper from session
          final wrapped = session.appWrapper(entry.widget);

          await tester.pumpWidget(wrapped);
          await tester.pumpAndSettle();

          // Precache images so they render in golden files
          final imageWidgets = find.byType(Image);
          if (imageWidgets.evaluate().isNotEmpty) {
            await tester.runAsync(() async {
              for (final element in imageWidgets.evaluate()) {
                final Image img = element.widget as Image;
                await precacheImage(img.image, element);
              }
            });
            await tester.pumpAndSettle();
          }

          final goldenPath = '../../$outputDir/\${entry.name}/\${deviceFrame.name}.png';

          await expectLater(
            find.byWidgetPredicate((w) => w == wrapped),
            matchesGoldenFile(goldenPath),
          );

          // Reset surface
          await tester.binding.setSurfaceSize(null);
        }
      }
    });
  });
}

DeviceFrame? _resolveDevice(String name) {
  const devices = <String, DeviceFrame>{
    'iphone_se': DeviceFrame.iPhoneSE,
    'iphone_14': DeviceFrame.iPhone14,
    'iphone_15_pro': DeviceFrame.iPhone15Pro,
    'iphone_16_pro_max': DeviceFrame.iPhone16ProMax,
    'ipad_mini': DeviceFrame.iPadMini,
    'ipad_air': DeviceFrame.iPadAir,
    'ipad_pro_11': DeviceFrame.iPadPro11,
    'ipad_pro_13': DeviceFrame.iPadPro13,
    'pixel_7': DeviceFrame.pixel7,
    'pixel_8_pro': DeviceFrame.pixel8Pro,
    'samsung_s24': DeviceFrame.samsungS24,
    'samsung_s24_ultra': DeviceFrame.samsungS24Ultra,
    'small': DeviceFrame.small,
    'medium': DeviceFrame.medium,
    'large': DeviceFrame.large,
    'compact': DeviceFrame.compact,
  };
  return devices[name];
}
''';
}

void _generateManifest(String outputDir) {
  final outDir = Directory(outputDir);
  if (!outDir.existsSync()) return;

  final screenshots = <Map<String, dynamic>>[];

  for (final widgetDir in outDir.listSync().whereType<Directory>()) {
    final widgetName = widgetDir.uri.pathSegments
        .where((s) => s.isNotEmpty)
        .last;

    for (final file in widgetDir.listSync().whereType<File>()) {
      if (!file.path.endsWith('.png')) continue;

      final fileName = file.uri.pathSegments.last;
      final deviceName = fileName.replaceAll('.png', '');

      screenshots.add({
        'name': widgetName,
        'file': '$widgetName/$fileName',
        'device': deviceName,
      });
    }
  }

  final manifest = {
    'generatedAt': DateTime.now().toUtc().toIso8601String(),
    'outputDir': outputDir,
    'screenshots': screenshots,
  };

  final manifestFile = File('$outputDir/manifest.json');
  manifestFile.writeAsStringSync(
    const JsonEncoder.withIndent('  ').convert(manifest),
  );
}
