/// Mechanical compiler from `_spec.json` (per-element DOM spec) to a Flutter
/// widget source file with literal values.
///
/// No tokens, no design-system components, no AI guessing — the generator
/// walks the decoded JSON tree and emits Dart directly. Output is
/// `dart format`-compatible after a single round-trip.
///
/// The caller owns file I/O. This library is pure functions so the unit tests
/// can exercise codegen without touching disk.
library;

import 'dart:convert';

/// Options that shape the generated file.
class ScaffoldGeneratorOptions {
  const ScaffoldGeneratorOptions({
    required this.className,
    required this.specRelativePath,
    required this.generatedAt,
    required this.regenerateCommand,
  });

  /// Name of the generated StatelessWidget class (e.g. `_KpiCardScaffold`).
  final String className;

  /// Path to the spec, relative to the project root, shown in the file header.
  final String specRelativePath;

  /// ISO-8601 UTC timestamp shown in the file header.
  final String generatedAt;

  /// Full `print_widget scaffold ...` incantation to reproduce the output.
  final String regenerateCommand;
}

/// Result of a scaffold generation pass — source plus metadata that the CLI
/// surfaces to the user.
class ScaffoldGeneratorResult {
  ScaffoldGeneratorResult({
    required this.source,
    required this.hasSvg,
    required this.todoCount,
  });

  /// The fully-formed `.dart` source string.
  final String source;

  /// Whether the tree contains a non-const `SvgPicture.string(...)`.
  /// Used by the CLI to surface `flutter_svg` requirement to the user.
  final bool hasSvg;

  /// Count of `// TODO:` markers emitted. Zero means every spec node was
  /// handled by a mechanical rule.
  final int todoCount;
}

/// Walks [spec] (a decoded `_spec.json` Map) and returns generated Dart code.
ScaffoldGeneratorResult generateScaffold(
  Map<String, dynamic> spec,
  ScaffoldGeneratorOptions options,
) {
  final root = spec['root'];
  if (root is! Map) {
    throw ArgumentError(
      'scaffold_generator: spec.root is missing or not an object',
    );
  }

  final ctx = _Ctx();
  final body = _emitNode(root.cast<String, dynamic>(), ctx, indent: 4);
  final header = _fileHeader(options);
  final imports = StringBuffer("import 'package:flutter/material.dart';\n");
  if (ctx.hasSvg) {
    imports.writeln("import 'package:flutter_svg/flutter_svg.dart';");
  }

  // When any SvgPicture.string(...) is in the tree, the root widget cannot be
  // `const`. Drop `const` from the default constructor too so the analyzer is
  // happy with the `return ...;` not being const.
  final constModifier = ctx.hasSvg ? '' : 'const ';

  final src = StringBuffer()
    ..write(header)
    ..writeln()
    ..write(imports)
    ..writeln()
    ..writeln('class ${options.className} extends StatelessWidget {')
    ..writeln('  $constModifier${options.className}({super.key});')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Widget build(BuildContext context) {')
    ..writeln('    return $body;')
    ..writeln('  }')
    ..writeln('}');

  return ScaffoldGeneratorResult(
    source: src.toString(),
    hasSvg: ctx.hasSvg,
    todoCount: ctx.todoCount,
  );
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

String _fileHeader(ScaffoldGeneratorOptions o) {
  return '// AUTO-GENERATED by print_widget scaffold — do not edit.\n'
      '// Source spec: ${o.specRelativePath}\n'
      '// Generated: ${o.generatedAt}\n'
      '// Regenerate: ${o.regenerateCommand}\n'
      '//\n'
      '// The scaffold uses literal values (no theme tokens, no custom components).\n'
      '// After layout converges with `print_widget compare`, run `print_widget tokenize`\n'
      '// to transform this file into the production widget with proper tokens.\n';
}

class _Ctx {
  bool hasSvg = false;
  int todoCount = 0;
}

String _emitNode(
  Map<String, dynamic> node,
  _Ctx ctx, {
  required int indent,
}) {
  // Leaf: SVG node
  if (node['svgHtml'] is String) {
    return _emitSvg(node, ctx, indent: indent);
  }

  // Leaf: text node
  if (node['text'] is String && (node['text'] as String).isNotEmpty) {
    return _emitText(node, ctx, indent: indent);
  }

  // `display: block` single-child wrapper with no styles → flatten.
  final styles =
      (node['styles'] as Map?)?.cast<String, dynamic>() ?? const {};
  final children = (node['children'] as List?)?.cast<Map>() ?? const <Map>[];
  if (children.length == 1 &&
      styles.isEmpty &&
      node['flexGrow'] == null) {
    return _emitNode(
      children.first.cast<String, dynamic>(),
      ctx,
      indent: indent,
    );
  }

  final childMaps = children.map((c) => c.cast<String, dynamic>()).toList();

  // Determine layout widget
  final display = styles['display'] as String?;
  final flexDir = styles['flexDirection'] as String?;
  final isFlex = display == 'flex' || display == 'inline-flex';
  final isColumn = isFlex && flexDir == 'column';
  final isRow = isFlex && (flexDir == null || flexDir == 'row');
  final isGrid = display == 'grid';
  final hasAbsoluteChild = childMaps.any((c) {
    final s = (c['styles'] as Map?)?.cast<String, dynamic>() ?? const {};
    return s['position'] == 'absolute';
  });

  String inner;
  if (hasAbsoluteChild) {
    inner = _emitStack(node, childMaps, styles, ctx, indent: indent);
  } else if (isColumn || isRow) {
    inner = _emitFlex(
      node,
      childMaps,
      styles,
      isColumn: isColumn,
      ctx: ctx,
      indent: indent,
    );
  } else if (isGrid) {
    ctx.todoCount++;
    inner = '${_emitWrap(childMaps, ctx, indent: indent)} // TODO: grid → review';
  } else if (childMaps.isEmpty) {
    // No children, no text, no svg — a pure shape / sizedbox.
    final bounds = (node['bounds'] as Map?)?.cast<String, dynamic>();
    final w = bounds?['w'];
    final h = bounds?['h'];
    if (w != null && h != null) {
      inner = 'SizedBox(width: ${_num(w)}, height: ${_num(h)})';
    } else {
      inner = 'SizedBox.shrink()';
    }
  } else if (childMaps.length == 1) {
    inner = _emitNode(childMaps.first, ctx, indent: indent);
  } else {
    // Unknown/unhandled container with multiple children → Stack-like fallback.
    ctx.todoCount++;
    final snippet = _todoSnippet(node);
    inner = '${_emitColumn(childMaps, ctx, indent: indent)} // TODO: manual layout — spec: $snippet';
  }

  // Apply wrappers. CSS semantics: padding is INSIDE the border/background,
  // margin is OUTSIDE. In Flutter, `Container(padding: ..., decoration: ...)`
  // puts the padding inside the decorated box — so when both are present we
  // emit a single Container with both. When only padding is present we emit
  // `Padding`; when only decoration is present we emit `Container`.
  final padding = (styles['padding'] as Map?)?.cast<String, dynamic>();
  final hasDecoration = _hasDecorationShape(node, styles);
  if (hasDecoration) {
    return _emitContainerWithDecoration(
      inner: inner,
      node: node,
      styles: styles,
      padding: padding,
      ctx: ctx,
      indent: indent,
    );
  }
  if (padding != null) {
    return _maybeWrapPadding(inner, padding, indent: indent);
  }
  return inner;
}

bool _hasDecorationShape(
  Map<String, dynamic> node,
  Map<String, dynamic> styles,
) {
  final bg = _parseColor(styles['backgroundColor']);
  final borderRadius = styles['borderRadius'];
  final boxShadow = styles['boxShadow'];
  if (bg != null) return true;
  if (borderRadius != null) return true;
  if (boxShadow is String && boxShadow.isNotEmpty && boxShadow != 'none') {
    return true;
  }
  // Pure shape leaf — also needs Container to give it size.
  final display = styles['display'] as String?;
  final isLayoutContainer = display == 'flex' ||
      display == 'inline-flex' ||
      display == 'grid';
  final needsExplicitSize = !isLayoutContainer &&
      (node['children'] == null ||
          (node['children'] as List).isEmpty) &&
      node['text'] == null &&
      node['svgHtml'] == null;
  return needsExplicitSize;
}

String _emitSvg(
  Map<String, dynamic> node,
  _Ctx ctx, {
  required int indent,
}) {
  ctx.hasSvg = true;
  final svg = node['svgHtml'] as String;
  final bounds = (node['bounds'] as Map?)?.cast<String, dynamic>();
  final w = bounds?['w'];
  final h = bounds?['h'];
  final buf = StringBuffer()..writeln('SvgPicture.string(');
  final pad = ' ' * (indent + 2);
  // Use triple single quotes and escape $ and any stray ''' sequences.
  final safe = svg.replaceAll(r"$", r"\$").replaceAll("'''", r"\'\'\'");
  buf.write(pad);
  buf.writeln("'''$safe''',");
  if (w != null) {
    buf
      ..write(pad)
      ..writeln('width: ${_num(w)},');
  }
  if (h != null) {
    buf
      ..write(pad)
      ..writeln('height: ${_num(h)},');
  }
  buf.write(' ' * indent);
  buf.write(')');
  return buf.toString();
}

String _emitText(
  Map<String, dynamic> node,
  _Ctx ctx, {
  required int indent,
}) {
  final text = node['text'] as String;
  final typ = (node['typography'] as Map?)?.cast<String, dynamic>();
  final styles =
      (node['styles'] as Map?)?.cast<String, dynamic>() ?? const {};
  final textOverflowFromTyp = typ?['textOverflow'] as String?;
  final overflow = styles['overflow'] as String?;
  final textOverflow = textOverflowFromTyp ?? styles['textOverflow'] as String?;

  final buf = StringBuffer()..writeln('Text(');
  final pad = ' ' * (indent + 2);
  buf
    ..write(pad)
    ..writeln("'${_dartStringEscape(text)}',");

  if (typ != null) {
    buf
      ..write(pad)
      ..writeln('style: TextStyle(');
    final sp = ' ' * (indent + 4);
    final family = typ['fontFamily'];
    if (family is String && family.isNotEmpty) {
      buf
        ..write(sp)
        ..writeln("fontFamily: '${_dartStringEscape(family)}',");
    }
    final fontSize = typ['fontSize'];
    if (fontSize is num) {
      buf
        ..write(sp)
        ..writeln('fontSize: ${_num(fontSize)},');
    }
    final weight = _mapFontWeight(typ['fontWeight']);
    if (weight != null) {
      buf
        ..write(sp)
        ..writeln('fontWeight: $weight,');
    }
    final color = _parseColor(typ['color']);
    if (color != null) {
      buf
        ..write(sp)
        ..writeln('color: $color,');
    }
    final height = _computeHeight(typ);
    if (height != null) {
      buf
        ..write(sp)
        ..writeln('height: ${_num(height)},');
    }
    final letterSpacing = _parsePxOrNum(typ['letterSpacing']);
    if (letterSpacing != null && letterSpacing != 0) {
      buf
        ..write(sp)
        ..writeln('letterSpacing: ${_num(letterSpacing)},');
    }
    buf
      ..write(pad)
      ..writeln('),');
  }

  final isEllipsis =
      (overflow == 'hidden' && textOverflow == 'ellipsis') ||
          textOverflow == 'ellipsis';
  if (isEllipsis) {
    buf
      ..write(pad)
      ..writeln('overflow: TextOverflow.ellipsis,')
      ..write(pad)
      ..writeln('maxLines: 1,');
  }

  buf.write(' ' * indent);
  buf.write(')');
  return buf.toString();
}

String _emitFlex(
  Map<String, dynamic> node,
  List<Map<String, dynamic>> children,
  Map<String, dynamic> styles, {
  required bool isColumn,
  required _Ctx ctx,
  required int indent,
}) {
  final widget = isColumn ? 'Column' : 'Row';
  final gap = (styles['gap'] as num?)?.toDouble();
  final alignItems = _mapCrossAxis(styles['alignItems'] as String?);
  final justifyContent = _mapMainAxis(styles['justifyContent'] as String?);

  final effectiveChildren = <Map<String, dynamic>>[];
  for (var i = 0; i < children.length; i++) {
    if (i > 0 && gap != null && gap > 0) {
      effectiveChildren.add({
        '__synthetic': 'gap',
        'gap': gap,
        'axis': isColumn ? 'column' : 'row',
      });
    }
    effectiveChildren.add(children[i]);
  }

  final buf = StringBuffer()..writeln('$widget(');
  final pad = ' ' * (indent + 2);
  if (alignItems != null) {
    buf
      ..write(pad)
      ..writeln('crossAxisAlignment: CrossAxisAlignment.$alignItems,');
  }
  if (justifyContent != null) {
    buf
      ..write(pad)
      ..writeln('mainAxisAlignment: MainAxisAlignment.$justifyContent,');
  }
  buf
    ..write(pad)
    ..writeln('children: [');
  final cp = ' ' * (indent + 4);
  for (final child in effectiveChildren) {
    buf.write(cp);
    if (child['__synthetic'] == 'gap') {
      final g = (child['gap'] as num).toDouble();
      buf.write(child['axis'] == 'column'
          ? 'SizedBox(height: ${_num(g)}),'
          : 'SizedBox(width: ${_num(g)}),');
      buf.writeln();
      continue;
    }
    final childStyles =
        (child['styles'] as Map?)?.cast<String, dynamic>() ?? const {};
    final flexGrow = (childStyles['flexGrow'] as num?) ?? (child['flexGrow'] as num?);
    var rendered = _emitNode(child, ctx, indent: indent + 4);
    if (flexGrow != null && flexGrow > 0) {
      rendered = 'Expanded(child: $rendered)';
    }
    buf.write(rendered);
    buf.writeln(',');
  }
  buf
    ..write(pad)
    ..writeln('],');
  buf.write(' ' * indent);
  buf.write(')');
  return buf.toString();
}

String _emitStack(
  Map<String, dynamic> node,
  List<Map<String, dynamic>> children,
  Map<String, dynamic> styles,
  _Ctx ctx, {
  required int indent,
}) {
  final buf = StringBuffer()..writeln('Stack(');
  final pad = ' ' * (indent + 2);
  buf
    ..write(pad)
    ..writeln('children: [');
  final cp = ' ' * (indent + 4);
  for (final child in children) {
    final cs =
        (child['styles'] as Map?)?.cast<String, dynamic>() ?? const {};
    final isAbs = cs['position'] == 'absolute';
    final rendered = _emitNode(child, ctx, indent: indent + 4);
    buf.write(cp);
    if (isAbs) {
      final top = _parsePxOrNum(cs['top']);
      final right = _parsePxOrNum(cs['right']);
      final bottom = _parsePxOrNum(cs['bottom']);
      final left = _parsePxOrNum(cs['left']);
      final parts = <String>[];
      if (top != null) parts.add('top: ${_num(top)}');
      if (right != null) parts.add('right: ${_num(right)}');
      if (bottom != null) parts.add('bottom: ${_num(bottom)}');
      if (left != null) parts.add('left: ${_num(left)}');
      parts.add('child: $rendered');
      buf.write('Positioned(${parts.join(', ')}),');
      buf.writeln();
    } else {
      buf
        ..write(rendered)
        ..writeln(',');
    }
  }
  buf
    ..write(pad)
    ..writeln('],');
  buf.write(' ' * indent);
  buf.write(')');
  return buf.toString();
}

String _emitColumn(
  List<Map<String, dynamic>> children,
  _Ctx ctx, {
  required int indent,
}) {
  final buf = StringBuffer()..writeln('Column(');
  final pad = ' ' * (indent + 2);
  buf
    ..write(pad)
    ..writeln('children: [');
  final cp = ' ' * (indent + 4);
  for (final c in children) {
    buf.write(cp);
    buf.write(_emitNode(c, ctx, indent: indent + 4));
    buf.writeln(',');
  }
  buf
    ..write(pad)
    ..writeln('],');
  buf.write(' ' * indent);
  buf.write(')');
  return buf.toString();
}

String _emitWrap(
  List<Map<String, dynamic>> children,
  _Ctx ctx, {
  required int indent,
}) {
  final buf = StringBuffer()..writeln('Wrap(');
  final pad = ' ' * (indent + 2);
  buf
    ..write(pad)
    ..writeln('children: [');
  final cp = ' ' * (indent + 4);
  for (final c in children) {
    buf.write(cp);
    buf.write(_emitNode(c, ctx, indent: indent + 4));
    buf.writeln(',');
  }
  buf
    ..write(pad)
    ..writeln('],');
  buf.write(' ' * indent);
  buf.write(')');
  return buf.toString();
}

/// Emit a `Container(...)` that carries decoration, optional padding, and
/// optional explicit width/height for pure-shape leaves.
String _emitContainerWithDecoration({
  required String inner,
  required Map<String, dynamic> node,
  required Map<String, dynamic> styles,
  required Map<String, dynamic>? padding,
  required _Ctx ctx,
  required int indent,
}) {
  final bg = _parseColor(styles['backgroundColor']);
  final borderRadius = styles['borderRadius'];
  final boxShadow = styles['boxShadow'];
  final isCircle = borderRadius == '50%' || borderRadius == 'circle';
  final hasShape = bg != null ||
      borderRadius != null ||
      (boxShadow is String && boxShadow != 'none' && boxShadow.isNotEmpty);

  final bounds = (node['bounds'] as Map?)?.cast<String, dynamic>();
  final width = bounds?['w'];
  final height = bounds?['h'];

  final display = styles['display'] as String?;
  final isLayoutContainer = display == 'flex' ||
      display == 'inline-flex' ||
      display == 'grid';
  final isLeafShape = !isLayoutContainer &&
      (node['children'] == null ||
          (node['children'] as List).isEmpty) &&
      node['text'] == null &&
      node['svgHtml'] == null;

  final buf = StringBuffer()..writeln('Container(');
  final pad = ' ' * (indent + 2);

  // Explicit size: either a circle (shape needs width==height) or a shape leaf
  // with no layout children.
  if ((isLeafShape || (isCircle && hasShape)) && width is num) {
    buf
      ..write(pad)
      ..writeln('width: ${_num(width)},');
  }
  if ((isLeafShape || (isCircle && hasShape)) && height is num) {
    buf
      ..write(pad)
      ..writeln('height: ${_num(height)},');
  }

  if (padding != null) {
    final edge = _edgeInsets(padding);
    if (edge != null) {
      buf
        ..write(pad)
        ..writeln('padding: $edge,');
    }
  }

  if (hasShape) {
    buf
      ..write(pad)
      ..writeln('decoration: BoxDecoration(');
    final sp = ' ' * (indent + 4);
    if (bg != null) {
      buf
        ..write(sp)
        ..writeln('color: $bg,');
    }
    if (isCircle) {
      buf
        ..write(sp)
        ..writeln('shape: BoxShape.circle,');
    } else if (borderRadius is num) {
      buf
        ..write(sp)
        ..writeln(
          'borderRadius: BorderRadius.circular(${_num(borderRadius)}),',
        );
    } else if (borderRadius is String) {
      final parsed = _parsePxOrNum(borderRadius);
      if (parsed != null) {
        buf
          ..write(sp)
          ..writeln(
            'borderRadius: BorderRadius.circular(${_num(parsed)}),',
          );
      }
    }
    if (boxShadow is String && boxShadow.isNotEmpty && boxShadow != 'none') {
      final shadow = _parseBoxShadow(boxShadow);
      if (shadow != null) {
        buf
          ..write(sp)
          ..writeln('boxShadow: $shadow,');
      } else {
        ctx.todoCount++;
        buf
          ..write(sp)
          ..writeln(
            '// TODO: unparsed boxShadow: ${_dartStringEscape(boxShadow)}',
          );
      }
    }
    buf
      ..write(pad)
      ..writeln('),');
  }

  // Inner widget: omit `child:` when the leaf has nothing to show.
  final showChild = inner != 'SizedBox.shrink()' &&
      !(isLeafShape && inner.startsWith('SizedBox(width:'));
  if (showChild) {
    buf
      ..write(pad)
      ..writeln('child: $inner,');
  }
  buf.write(' ' * indent);
  buf.write(')');
  return buf.toString();
}

String _maybeWrapPadding(
  String inner,
  Map<String, dynamic> padding, {
  required int indent,
}) {
  final edge = _edgeInsets(padding);
  if (edge == null) return inner;
  final buf = StringBuffer()..writeln('Padding(');
  final pad = ' ' * (indent + 2);
  buf
    ..write(pad)
    ..writeln('padding: $edge,')
    ..write(pad)
    ..writeln('child: $inner,');
  buf.write(' ' * indent);
  buf.write(')');
  return buf.toString();
}

/// Collapses {top, right, bottom, left} to the shortest EdgeInsets form.
/// Returns null when all sides are zero.
String? _edgeInsets(Map<String, dynamic> padding) {
  final top = (padding['top'] as num?)?.toDouble() ?? 0;
  final right = (padding['right'] as num?)?.toDouble() ?? 0;
  final bottom = (padding['bottom'] as num?)?.toDouble() ?? 0;
  final left = (padding['left'] as num?)?.toDouble() ?? 0;
  if (top == 0 && right == 0 && bottom == 0 && left == 0) return null;
  if (top == right && right == bottom && bottom == left) {
    return 'EdgeInsets.all(${_num(top)})';
  }
  if (top == bottom && left == right) {
    return 'EdgeInsets.symmetric(horizontal: ${_num(left)}, vertical: ${_num(top)})';
  }
  return 'EdgeInsets.fromLTRB(${_num(left)}, ${_num(top)}, ${_num(right)}, ${_num(bottom)})';
}

// ---------------------------------------------------------------------------
// Value parsing
// ---------------------------------------------------------------------------

/// Turn any CSS color string into a Dart `Color(0xAARRGGBB)` literal.
///
/// Returns `null` for transparent / null / unparseable inputs so the caller
/// can omit the property entirely.
String? _parseColor(Object? raw) {
  if (raw == null) return null;
  if (raw is! String) return null;
  final v = raw.trim().toLowerCase();
  if (v.isEmpty) return null;
  if (v == 'transparent') return null;

  // Hex forms: #RGB, #RGBA, #RRGGBB, #RRGGBBAA
  if (v.startsWith('#')) {
    var hex = v.substring(1);
    if (hex.length == 3 || hex.length == 4) {
      hex = hex.split('').map((c) => '$c$c').join();
    }
    if (hex.length == 6) {
      return 'Color(0xFF${hex.toUpperCase()})';
    }
    if (hex.length == 8) {
      // CSS puts alpha LAST; Flutter puts it FIRST. Reorder.
      final rgb = hex.substring(0, 6);
      final a = hex.substring(6, 8);
      if (a == '00') return null;
      return 'Color(0x${a.toUpperCase()}${rgb.toUpperCase()})';
    }
    return null;
  }

  // rgb(R,G,B) / rgba(R,G,B,A)
  final rgbaRe = RegExp(
    r'^rgba?\s*\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)$',
  );
  final m = rgbaRe.firstMatch(v);
  if (m != null) {
    final r = int.tryParse(m.group(1)!) ?? double.parse(m.group(1)!).round();
    final g = int.tryParse(m.group(2)!) ?? double.parse(m.group(2)!).round();
    final b = int.tryParse(m.group(3)!) ?? double.parse(m.group(3)!).round();
    final aStr = m.group(4);
    int a = 255;
    if (aStr != null) {
      final af = double.tryParse(aStr) ?? 1.0;
      if (af <= 0) return null;
      a = (af * 255).round().clamp(0, 255);
    }
    return 'Color(0x${_hex2(a)}${_hex2(r)}${_hex2(g)}${_hex2(b)})';
  }
  return null;
}

String _hex2(int v) => v.toRadixString(16).padLeft(2, '0').toUpperCase();

/// Parses values like `"12px"` or `12` into a double. Returns null for
/// `"normal"`, `"auto"`, null, etc.
double? _parsePxOrNum(Object? raw) {
  if (raw == null) return null;
  if (raw is num) return raw.toDouble();
  if (raw is! String) return null;
  final trimmed = raw.trim();
  if (trimmed.isEmpty) return null;
  if (trimmed == 'normal' || trimmed == 'auto' || trimmed == 'none') {
    return null;
  }
  final m = RegExp(r'^(-?[\d.]+)\s*px?$').firstMatch(trimmed);
  if (m != null) return double.tryParse(m.group(1)!);
  return double.tryParse(trimmed);
}

String? _mapFontWeight(Object? raw) {
  if (raw == null) return null;
  int? w;
  if (raw is num) {
    w = raw.toInt();
  } else if (raw is String) {
    final t = raw.trim().toLowerCase();
    if (t == 'bold') return 'FontWeight.bold';
    if (t == 'normal') return 'FontWeight.w400';
    w = int.tryParse(t);
  }
  if (w == null) return null;
  // Snap to nearest 100 in [100, 900].
  final snapped = ((w / 100).round() * 100).clamp(100, 900);
  return 'FontWeight.w$snapped';
}

/// Computes a `height:` multiplier for a TextStyle from the spec's `lineHeight`
/// and `fontSize`. Returns null when either isn't a number.
double? _computeHeight(Map<String, dynamic> typ) {
  final lh = typ['lineHeight'];
  final fs = typ['fontSize'];
  if (lh is! num || fs is! num || fs == 0) return null;
  // Round to 3 decimals to keep the emitted source stable.
  final ratio = (lh / fs);
  return (ratio * 1000).round() / 1000;
}

String? _mapCrossAxis(String? v) {
  if (v == null) return null;
  switch (v) {
    case 'center':
      return 'center';
    case 'flex-start':
    case 'start':
      return 'start';
    case 'flex-end':
    case 'end':
      return 'end';
    case 'stretch':
      return 'stretch';
    case 'baseline':
      return 'baseline';
    default:
      return null;
  }
}

String? _mapMainAxis(String? v) {
  if (v == null) return null;
  switch (v) {
    case 'center':
      return 'center';
    case 'flex-start':
    case 'start':
      return 'start';
    case 'flex-end':
    case 'end':
      return 'end';
    case 'space-between':
      return 'spaceBetween';
    case 'space-around':
      return 'spaceAround';
    case 'space-evenly':
      return 'spaceEvenly';
    default:
      return null;
  }
}

/// Parse a single `box-shadow` value like `0 1px 3px rgba(0,0,0,0.1)`.
/// Returns a Dart list-literal string or null if we can't parse.
String? _parseBoxShadow(String raw) {
  // Split by commas NOT inside parentheses (handles multi-shadow).
  final parts = <String>[];
  int depth = 0;
  final buf = StringBuffer();
  for (final ch in raw.split('')) {
    if (ch == '(') depth++;
    if (ch == ')') depth--;
    if (ch == ',' && depth == 0) {
      parts.add(buf.toString().trim());
      buf.clear();
      continue;
    }
    buf.write(ch);
  }
  if (buf.isNotEmpty) parts.add(buf.toString().trim());

  final shadows = <String>[];
  for (final part in parts) {
    final s = _parseSingleShadow(part);
    if (s == null) return null;
    shadows.add(s);
  }
  if (shadows.isEmpty) return null;
  return '[${shadows.join(', ')}]';
}

String? _parseSingleShadow(String part) {
  // Extract a color() chunk first.
  final colorMatch = RegExp(
    r'(rgba?\([^)]*\)|#[0-9a-fA-F]{3,8}|transparent)',
  ).firstMatch(part);
  if (colorMatch == null) return null;
  final colorStr = colorMatch.group(1)!;
  final color = _parseColor(colorStr);
  if (color == null) return null;
  final remainder =
      part.replaceFirst(colorMatch.group(1)!, '').trim();
  final tokens = remainder.split(RegExp(r'\s+')).where((t) => t.isNotEmpty).toList();
  final nums = <double>[];
  for (final t in tokens) {
    final n = _parsePxOrNum(t);
    if (n == null) break;
    nums.add(n);
  }
  if (nums.length < 2) return null;
  final offsetX = nums[0];
  final offsetY = nums[1];
  final blur = nums.length > 2 ? nums[2] : 0.0;
  final spread = nums.length > 3 ? nums[3] : 0.0;
  final props = <String>[
    'color: $color',
    'offset: Offset(${_num(offsetX)}, ${_num(offsetY)})',
    if (blur != 0) 'blurRadius: ${_num(blur)}',
    if (spread != 0) 'spreadRadius: ${_num(spread)}',
  ];
  return 'BoxShadow(${props.join(', ')})';
}

String _todoSnippet(Map<String, dynamic> node) {
  final summary = <String, dynamic>{
    'tag': node['tag'],
    if (node['styles'] != null) 'styles': node['styles'],
    if (node['children'] is List)
      'children': '${(node['children'] as List).length} child(ren)',
  };
  final s = jsonEncode(summary);
  // Keep the snippet line-length friendly.
  return s.length > 140 ? '${s.substring(0, 137)}...' : s;
}

/// Render a number as the shortest literal that round-trips — `40` instead of
/// `40.0`, but `1.25` stays as-is.
String _num(num n) {
  final d = n.toDouble();
  if (d == d.truncateToDouble() && d.abs() < 1e16) {
    return d.toInt().toString();
  }
  // Trim trailing zeros (e.g. 1.500 → 1.5).
  var s = d.toString();
  if (s.contains('.')) {
    s = s.replaceFirst(RegExp(r'0+$'), '');
    if (s.endsWith('.')) s = s.substring(0, s.length - 1);
  }
  return s;
}

String _dartStringEscape(String s) {
  final buf = StringBuffer();
  for (var i = 0; i < s.length; i++) {
    final c = s[i];
    if (c == r'\') {
      buf.write(r'\\');
    } else if (c == "'") {
      buf.write(r"\'");
    } else if (c == r'$') {
      buf.write(r'\$');
    } else if (c == '\n') {
      buf.write(r'\n');
    } else if (c == '\r') {
      buf.write(r'\r');
    } else if (c == '\t') {
      buf.write(r'\t');
    } else {
      buf.write(c);
    }
  }
  return buf.toString();
}

